version: "3"

services:
  sora:
    build:
      context: .
      dockerfile: ./apps/sora/Dockerfile
      args:
        TURBO_TOKEN: ${TURBO_TOKEN}
        TURBO_TEAM: ${TURBO_TEAM}
        TURBO_API: ${TURBO_API}
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - sora_data:/app/apps/web/public/uploads
    depends_on:
      - rabbitmq
      - mariadb
      - vote-processor
    networks:
      - database
      - queue
    environment:
      AMQP_URL: "amqp://rabbitmq"
      DATABASE_URL: "mysql://root:${DATABASE_PASSWORD}@mariadb/${DATABASE_NAME:-sora}"
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: "http://localhost:3000/"
      SETTINGS_SECRET: ${SETTINGS_SECRET}

  vote-processor:
    build:
      context: .
      dockerfile: ./apps/vote-processor/Dockerfile
      args:
        TURBO_TOKEN: ${TURBO_TOKEN}
        TURBO_TEAM: ${TURBO_TEAM}
        TURBO_API: ${TURBO_API}
    depends_on:
      - rabbitmq
      - mariadb
    networks:
      - database
      - queue
    environment:
      AMQP_URL: "amqp://rabbitmq"
      DATABASE_URL: "mysql://root:${DATABASE_PASSWORD}@mariadb/${DATABASE_NAME:-sora}"
      TRPC_URL: "http://sora/api/trpc" # Don't change this line

  rabbitmq:
    image: rabbitmq:3.11.13-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - queue

  mariadb:
    image: mariadb:10.11.2
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME:-sora}
      MYSQL_ROOT_HOST: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - database

volumes:
  rabbitmq_data:
  mariadb_data:
  sora_data:

networks:
  database:
    driver: bridge
  queue:
    driver: bridge
