version: "3"

services:
  sora:
    build:
      context: .
      dockerfile: ./apps/sora/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./apps/sora/public/uploads:/app/public/uploads
      # - ./apps/sora/settings.bin:/app/settings.bin
    depends_on:
      - rabbitmq
      - mariadb
      - vote-processor
    environment:
      AMQP_URL: "amqp://rabbitmq"
      DATABASE_URL: "mysql://root:password@mariadb/sora"
      NEXTAUTH_SECRET: "very_super_secret_for_auth"
      NEXTAUTH_URL: "http://localhost:3000/"
      SETTINGS_SECRET: "VERY_SUPER_SECRET_FOR_SETTINGS"

  vote-processor:
    build:
      context: .
      dockerfile: ./apps/vote-processor/Dockerfile
    depends_on:
      - rabbitmq
      - mariadb
    environment:
      AMQP_URL: "amqp://rabbitmq"
      DATABASE_URL: "mysql://root:password@mariadb/sora"
      TRPC_URL: "http://sora/api/trpc"

  rabbitmq:
    image: rabbitmq:3.11.13-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  mariadb:
    image: mariadb:10.11.2
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: sora
      MARIADB_MYSQL_LOCALHOST_USER: user
      MYSQL_ROOT_HOST: mariadb
      MARIADB_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  rabbitmq_data:
  mariadb_data:
