version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  linux: &linux-executor
    machine:
      image: ubuntu-2004:2023.04.2
  win: &win-executor
    machine:
      image: windows-server-2022-gui:current
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass

jobs:
  desktop-builder:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout

      - when:
          condition:
            equal: [*linux-executor, << parameters.os >>]
          steps:
            - node/install:
                node-version: "18.15.0"
      - when:
          condition:
            equal: [*win-executor, << parameters.os >>]
          steps:
            - run: choco install wget -y
            - run:
                command: wget https://nodejs.org/dist/v18.15.0/node-v18.15.0-x86.msi -P C:\Users\circleci\Downloads\
                shell: cmd.exe
            - run: MsiExec.exe /i C:\Users\circleci\Downloads\node-v18.15.0-x86.msi /qn
            - run:
                command: |
                  Start-Process powershell -verb runAs -Args "-start GeneralProfile"
                  nvm install 18.15.0
                  nvm use 18.15.0

      - run: node --version
      - run:
          name: Using latest yarn
          command: |
            corepack enable
            corepack prepare yarn@stable --activate
      - run: yarn -v
      - run:
          name: Install all dependencies
          command: |
            yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged

      - run:
          name: Test Code Linting
          command: |
            yarn lint
      - run:
          name: Prisma generate
          command: |
            yarn generate
      - run:
          name: Typescript typechecking
          command: |
            yarn typecheck

workflows:
  all-builds:
    jobs:
      - desktop-builder:
          matrix:
            parameters:
              os: [linux, win]
