name: Lint, TS, Prettier Check
on: [pull_request, push]

env:
  AMQP_URL: amqp://localhost
  DATABASE_URL: mysql://usrnm:pw@localhost:3306/sora
  NEXTAUTH_SECRET: dummysecret
  NEXTAUTH_URL: http://localhost:3000
  SETTINGS_SECRET: dummysecret

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Mengecek apakah file aman dari segi typing dan linting, juga prettier

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install all dependencies
        uses: ./.github/actions/yarn-nm-install

      - name: Test Prettier
        run: yarn format:check

      - name: Test Code Linting
        run: yarn lint

      - name: Test Typing
        run: yarn typecheck
