name: End to End testing for web
on: [pull_request, push]

env:
  DATABASE_URL: "mysql://root:password@localhost:3306/sora-test-e2e"
  NEXTAUTH_SECRET: "askdhsakjndkasudasludaksjd"
  NEXTAUTH_URL: "http://localhost:3000"
  AMQP_URL: "amqp://localhost"

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install all dependencies
        uses: ./.github/actions/yarn-nm-install

      - name: Pull MariaDB image
        run: docker pull mariadb

      - name: Start MariaDB container
        run: |
          docker run -d --name mariadb_container -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password mariadb

      - name: Wait for MariaDB port
        run: |
          until nc -z localhost 3306; do sleep 1; done

      - name: Test Prettier
        run: yarn format:check

      - name: Test Code Linting
        run: yarn lint

      - name: Test Typing
        run: yarn type-check

      - name: Build web
        run: yarn turbo run build --filter=@sora/web 

      - name: Run E2E
        run: yarn e2e
