name: ES Lint
on: [pull_request, push]

env:
  DATABASE_URL: mysql://usrnm:pw@localhost:3306/sora
  NEXTAUTH_SECRET: dummysecret
  NEXTAUTH_URL: http://localhost:3000
  SETTINGS_SECRET: dummysecret

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Mengecek apakah file aman lint eslint

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install all dependencies
        uses: ./.github/actions/yarn-nm-install

      - name: Test Code Linting
        run: yarn lint
